spring:
  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/soldout_db?characterEncoding=UTF-8
        username: soldout
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: false

    slave:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/soldout_db?characterEncoding=UTF-8
        username: soldout
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  redis:
    host: localhost
    port: 6379
    session:
      timeout: 10
      store-type: redis

mybatis:
  type-aliases-package: api.soldout.io.soldout.mapper
  mapper-locations: classpath:mapper/*.xml

session:
  interval: 10
  db:
    expiration: 10

jwt:
  secretKey: aasjjkjaskjdl1k2naskjkdakj34c8sasdfwefwefw156434wegwef
  ttlMillis: 120000