spring:
  datasource:
  url: jdbc-url:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8
                                           &serverTimezone=GMT%2B8
                                           &useSSL=false
                                           &allowPublicKeyRetrieval=true
  username: soldout
  password: 1234

mybatis:
  type-aliases-package: api.soldout.io.soldout.mapper
  mapper-locations: classpath:mapper/*.xml

session:
  interval: 10
  db:
    expiration: 10

jwt:
  secretKey: aasjjkjaskjdl1k2naskjkdakj34c8sasdfwefwefw156434wegwef
  ttlMillis: 120000